/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as AgentPropertiesRouteImport } from './routes/agent/properties'
import { Route as AgentInquiriesRouteImport } from './routes/agent/inquiries'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AgentPropertyNewRouteImport } from './routes/agent/property.new'
import { Route as AgentPropertiesNewRouteImport } from './routes/agent/properties.new'
import { Route as AgentPropertyIdEditRouteImport } from './routes/agent/property.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPropertiesRoute = AgentPropertiesRouteImport.update({
  id: '/agent/properties',
  path: '/agent/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentInquiriesRoute = AgentInquiriesRouteImport.update({
  id: '/agent/inquiries',
  path: '/agent/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPropertyNewRoute = AgentPropertyNewRouteImport.update({
  id: '/agent/property/new',
  path: '/agent/property/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPropertiesNewRoute = AgentPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentPropertiesRoute,
} as any)
const AgentPropertyIdEditRoute = AgentPropertyIdEditRouteImport.update({
  id: '/agent/property/$id/edit',
  path: '/agent/property/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/inquiries': typeof AgentInquiriesRoute
  '/agent/properties': typeof AgentPropertiesRouteWithChildren
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/agent/properties/new': typeof AgentPropertiesNewRoute
  '/agent/property/new': typeof AgentPropertyNewRoute
  '/agent/property/$id/edit': typeof AgentPropertyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/inquiries': typeof AgentInquiriesRoute
  '/agent/properties': typeof AgentPropertiesRouteWithChildren
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/agent/properties/new': typeof AgentPropertiesNewRoute
  '/agent/property/new': typeof AgentPropertyNewRoute
  '/agent/property/$id/edit': typeof AgentPropertyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/inquiries': typeof AgentInquiriesRoute
  '/agent/properties': typeof AgentPropertiesRouteWithChildren
  '/properties/$slug': typeof PropertiesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/agent/properties/new': typeof AgentPropertiesNewRoute
  '/agent/property/new': typeof AgentPropertyNewRoute
  '/agent/property/$id/edit': typeof AgentPropertyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/users'
    | '/agent/inquiries'
    | '/agent/properties'
    | '/properties/$slug'
    | '/admin/'
    | '/agent/'
    | '/properties/'
    | '/agent/properties/new'
    | '/agent/property/new'
    | '/agent/property/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/users'
    | '/agent/inquiries'
    | '/agent/properties'
    | '/properties/$slug'
    | '/admin'
    | '/agent'
    | '/properties'
    | '/agent/properties/new'
    | '/agent/property/new'
    | '/agent/property/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/users'
    | '/agent/inquiries'
    | '/agent/properties'
    | '/properties/$slug'
    | '/admin/'
    | '/agent/'
    | '/properties/'
    | '/agent/properties/new'
    | '/agent/property/new'
    | '/agent/property/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AgentInquiriesRoute: typeof AgentInquiriesRoute
  AgentPropertiesRoute: typeof AgentPropertiesRouteWithChildren
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  AgentPropertyNewRoute: typeof AgentPropertyNewRoute
  AgentPropertyIdEditRoute: typeof AgentPropertyIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/properties': {
      id: '/agent/properties'
      path: '/agent/properties'
      fullPath: '/agent/properties'
      preLoaderRoute: typeof AgentPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/inquiries': {
      id: '/agent/inquiries'
      path: '/agent/inquiries'
      fullPath: '/agent/inquiries'
      preLoaderRoute: typeof AgentInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/property/new': {
      id: '/agent/property/new'
      path: '/agent/property/new'
      fullPath: '/agent/property/new'
      preLoaderRoute: typeof AgentPropertyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/properties/new': {
      id: '/agent/properties/new'
      path: '/new'
      fullPath: '/agent/properties/new'
      preLoaderRoute: typeof AgentPropertiesNewRouteImport
      parentRoute: typeof AgentPropertiesRoute
    }
    '/agent/property/$id/edit': {
      id: '/agent/property/$id/edit'
      path: '/agent/property/$id/edit'
      fullPath: '/agent/property/$id/edit'
      preLoaderRoute: typeof AgentPropertyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentPropertiesRouteChildren {
  AgentPropertiesNewRoute: typeof AgentPropertiesNewRoute
}

const AgentPropertiesRouteChildren: AgentPropertiesRouteChildren = {
  AgentPropertiesNewRoute: AgentPropertiesNewRoute,
}

const AgentPropertiesRouteWithChildren = AgentPropertiesRoute._addFileChildren(
  AgentPropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AgentInquiriesRoute: AgentInquiriesRoute,
  AgentPropertiesRoute: AgentPropertiesRouteWithChildren,
  PropertiesSlugRoute: PropertiesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  AgentPropertyNewRoute: AgentPropertyNewRoute,
  AgentPropertyIdEditRoute: AgentPropertyIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
